In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
xs1 = np.random.choice(range(5), size=20)
xs2 = np.zeros(shape=20)

In [3]:
xs1, xs2

(array([3, 2, 3, 2, 4, 2, 1, 0, 2, 2, 1, 2, 3, 3, 0, 2, 2, 2, 1, 0]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]))

In [4]:
scaler = StandardScaler()

In [5]:
scaler.fit_transform(xs1.reshape(-1,1)).flatten()

array([ 1.0830277 ,  0.14126448,  1.0830277 ,  0.14126448,  2.02479092,
        0.14126448, -0.80049874, -1.74226195,  0.14126448,  0.14126448,
       -0.80049874,  0.14126448,  1.0830277 ,  1.0830277 , -1.74226195,
        0.14126448,  0.14126448,  0.14126448, -0.80049874, -1.74226195])

In [6]:
scaler.fit_transform(xs2.reshape(-1,1)).flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [8]:
scaler.fit_transform([[0,0,0]])

array([[0., 0., 0.]])